Speakers:
  Spk1:
    Port: "DAC9"
    Tone: "ToneStim"
    Noise: "NoiseStim"
    File: "FileStim"
    Selectors: [ "StimSel", "SyncSel" ]
    Records: [ "AudioStimRec", "AudioSyncRec" ]

Digital:
  PhotoDiode:
    Type: "Input"
    Records: [ "PhotoDiodeRec" ]
  NPXSync:
    Type: "Output"
    Command: "SyncSig"
    Records: [ "NeuP" ]
